<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>21920914-d11f-4fb9-87ef-8cd972d8bbea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client_role']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client_role</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>992627ed-dae9-4f25-9557-9f9b40be93e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client_role</value>
      <webElementGuid>e42be6a6-620a-45e6-9b9f-535aa2e1b051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client_role</value>
      <webElementGuid>224c57c2-da2a-453e-882d-beee64fbffac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selectpicker col-md-9</value>
      <webElementGuid>d9d70499-d15a-48d7-9be8-4def1c5e189c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>إختر دور العميل</value>
      <webElementGuid>03a6bc24-04fb-4435-bc9b-12fcc6a38216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>5468c92d-1873-45ff-b78a-035429166a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            عميل
                                مورد
                                كلاهما
                                                    </value>
      <webElementGuid>43193123-2e82-44a3-8c81-b3929a64f0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client_role&quot;)</value>
      <webElementGuid>f08a998a-3be0-4c6d-a0dc-7c9ae95135e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client_role']</value>
      <webElementGuid>034a48cc-57df-485c-979e-17ae51d9790f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دور العميل :'])[1]/following::select[1]</value>
      <webElementGuid>c6968bc9-cd57-4b50-aa7c-be9b92b0d8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عميل جديد'])[1]/following::select[1]</value>
      <webElementGuid>9c0f2d9c-c7e9-4f3d-9b78-558e1893e336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إختر دور العميل'])[1]/preceding::select[1]</value>
      <webElementGuid>5ce53976-a2c6-4717-b8ab-5399a7570660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عميل'])[2]/preceding::select[1]</value>
      <webElementGuid>72d61f01-934d-4c39-a14d-9aa54f16f615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>df9c5643-2348-4ae8-bb49-be1d0b0f1a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'client_role' and @id = 'client_role' and @title = 'إختر دور العميل' and (text() = '
                                                            عميل
                                مورد
                                كلاهما
                                                    ' or . = '
                                                            عميل
                                مورد
                                كلاهما
                                                    ')]</value>
      <webElementGuid>b4a6cfd7-4968-4d28-899a-5901843dddda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
