<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>5584ea3d-452e-48e4-aeaf-2a78bea8ef5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-1-0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d0ee9bac-1588-4d97-8432-aef06ec852da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edf161d6-831d-4c81-9ed4-31c502ccf543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>عميل</value>
      <webElementGuid>21fbe4ea-9b88-43b2-b408-50b440fa898f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-1-0&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>7dfeebe7-81fd-40bb-a66c-b9396f54450d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-1-0']/span</value>
      <webElementGuid>87d4691f-abd6-4806-bf98-3ce5f102b688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إختر دور العميل'])[1]/following::span[1]</value>
      <webElementGuid>8d43896f-46f8-41f7-9509-6aed1ae65919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دور العميل :'])[1]/following::span[1]</value>
      <webElementGuid>806f6bb0-8663-49f3-81f2-efdf035f78dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مورد'])[2]/preceding::span[1]</value>
      <webElementGuid>d1cd8901-abd5-4d0c-8726-03faaa19c723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='كلاهما'])[2]/preceding::span[2]</value>
      <webElementGuid>6a9e4aae-2852-4e53-81cf-153d3c78f7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/a/span</value>
      <webElementGuid>0f22a8f2-ce43-4208-8609-5b3ea5cf8312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'عميل' or . = 'عميل')]</value>
      <webElementGuid>7307ec35-229b-489d-b941-12e55b056292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
