<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arrange_type</name>
   <tag></tag>
   <elementGuidId>ef0a48fc-2768-47be-9ba6-249d6cdc4e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arrange_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arrange_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaacfc1a-e7c7-4322-940c-c57b4861f789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9c3f6fd1-4bd3-4ba6-8e6a-625444682a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-sm-1</value>
      <webElementGuid>8a0f95f7-c0e8-4466-a9e6-d41d60108587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arrange_type</value>
      <webElementGuid>bcb11353-2f9f-45a3-9b0d-9138fd6dcaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arrange_type</value>
      <webElementGuid>14ef1a80-676f-4796-ba4a-243fc10290e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrange_type&quot;)</value>
      <webElementGuid>8395f3e2-58f5-43e4-bbf2-5c60d4ba5ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arrange_type']</value>
      <webElementGuid>a397cd29-77ad-4c1c-9c7e-2886b869b61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-loader-u']/div/div/div/div[5]/input</value>
      <webElementGuid>ed13f1bf-c8c5-4751-b72a-0e810dbde507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>70e19e4e-5f2e-48ab-be8a-9c02d6e6c1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'arrange_type' and @id = 'arrange_type']</value>
      <webElementGuid>b524da3e-3bdc-4f04-8ef1-391cb84978c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
