<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arrange_type</name>
   <tag></tag>
   <elementGuidId>0dc27864-e6f5-4362-9e67-a4a19717617e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group.d-flex.styl > #arrange_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='arrange_type'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b5fad34-ab7c-4167-a6aa-7f97a6800762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5ed941a6-5ce9-48b4-b395-d81d96e8d1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-sm-1</value>
      <webElementGuid>02e56c92-01a9-4f05-9720-b2594641671a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arrange_type</value>
      <webElementGuid>0e1d664c-26ff-43aa-8166-1faa0674a780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arrange_type</value>
      <webElementGuid>731c8f3d-15e2-415f-aab8-66cba1b9d571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updateElementWell&quot;)/div[@class=&quot;form-group d-flex styl&quot;]/input[@id=&quot;arrange_type&quot;]</value>
      <webElementGuid>324076f3-4dd5-45db-b711-3539192cce42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='arrange_type'])[2]</value>
      <webElementGuid>dca5a0b2-84e9-408a-866c-d14f90a3bcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateElementWell']/div[5]/input</value>
      <webElementGuid>6e48218f-b241-4932-af60-062dd399b20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[5]/input</value>
      <webElementGuid>1fe4ef46-e10b-4152-8aef-68c47e700b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'arrange_type' and @id = 'arrange_type']</value>
      <webElementGuid>53e81f3a-e5f0-4992-ae61-fc25fdb7df7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
