<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arrange_type</name>
   <tag></tag>
   <elementGuidId>06d1b65f-ddbb-4ca3-801c-f156bf3560db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arrange_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arrange_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>382e2ef8-290c-4426-8c24-70928187aaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7d726fa8-df76-4a17-bc1c-cfc25dc8c087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-sm-1</value>
      <webElementGuid>5b50fd40-8fbd-4a5b-8fa3-2895ece1c03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arrange_type</value>
      <webElementGuid>cd4cbb25-8bce-407f-bc44-d85907cabee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arrange_type</value>
      <webElementGuid>b4efbf15-c4db-4bed-b8c2-0a03d446d281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrange_type&quot;)</value>
      <webElementGuid>610bb750-ae07-40a5-95e2-3c926193900d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arrange_type']</value>
      <webElementGuid>b9f41544-ba4b-4892-89e3-74cd6b89dbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-loader-u']/div/div/div/div[5]/input</value>
      <webElementGuid>47129009-9bbb-485a-9c07-087189f410a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>6cb01c36-d6d1-427c-a981-08253751f445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'arrange_type' and @id = 'arrange_type']</value>
      <webElementGuid>252522c0-5231-49c5-89c4-05617b8cdf19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
