<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arrange_type</name>
   <tag></tag>
   <elementGuidId>93e62056-9c27-411e-aaf1-54f6419d066d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arrange_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arrange_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5730ef21-0ae6-4895-97fc-354a05fd7b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7d24c1c2-f5f8-4442-b5a8-e501e978de3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-sm-1</value>
      <webElementGuid>bba1cc37-3e4b-4b11-925e-3beb1a738a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arrange_type</value>
      <webElementGuid>6c99a57a-c0c0-4cb8-a129-e289ff6fa1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arrange_type</value>
      <webElementGuid>d20e1467-a220-48c3-80a8-a4b8e1c4070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arrange_type&quot;)</value>
      <webElementGuid>9cf65c1a-c692-4612-804f-58a529564a05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arrange_type']</value>
      <webElementGuid>ed84e793-0268-48b7-94a1-c54d202885e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-loader-u']/div/div/div/div[5]/input</value>
      <webElementGuid>bff271db-4476-49e9-a24a-2d22483405ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>4516542b-cb93-40aa-bfeb-6feca8d5b0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'arrange_type' and @id = 'arrange_type']</value>
      <webElementGuid>8a3cba9a-5d85-4dbf-bebb-f882f1ad121b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
