<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>0669c5dd-703f-48b7-a4e9-3d4dff25fd97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client_role']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client_role</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fa98a3bc-47ea-46eb-80d7-55300d03343a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client_role</value>
      <webElementGuid>bd3d3449-b8d7-4042-92ab-ed7843341dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client_role</value>
      <webElementGuid>19f0f747-dd01-47f5-a326-6dbd83420f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selectpicker col-md-9</value>
      <webElementGuid>4b8635ad-6635-42d2-b4c5-1cd3e730c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>اختر دور العميل أو المورد</value>
      <webElementGuid>0807e3e1-3ee1-4e31-9d93-0915450583fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>7c3eb66d-704c-4686-9d0b-263e3be02ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                عميل
                                                                                                    مورد
                                                                كلاهما
                                                    </value>
      <webElementGuid>301567bb-b93a-49a7-a9aa-c0fbb1a6236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client_role&quot;)</value>
      <webElementGuid>35928c4e-86c9-4e3e-bca2-620f3c6d2cb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client_role']</value>
      <webElementGuid>95243ac7-0e0b-4b6f-b1c6-c0c4b189a4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دور العميل أو المورد :'])[1]/following::select[1]</value>
      <webElementGuid>d3a51241-074c-48a8-9cf1-1585e9fbdb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عميل أو مورد جديد'])[1]/following::select[1]</value>
      <webElementGuid>668407b4-a7df-4534-9907-f5ee2cc11e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر دور العميل أو المورد'])[1]/preceding::select[1]</value>
      <webElementGuid>e9d7aa06-f565-4b81-a1f3-9685ac822082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عميل'])[2]/preceding::select[1]</value>
      <webElementGuid>26b8bf63-fe70-4e5b-8d63-8f38a8e8f270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>66e2b783-fa1c-4fc0-ba5f-f22cdc8ef27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'client_role' and @id = 'client_role' and @title = 'اختر دور العميل أو المورد' and (text() = '
                                                                                                عميل
                                                                                                    مورد
                                                                كلاهما
                                                    ' or . = '
                                                                                                عميل
                                                                                                    مورد
                                                                كلاهما
                                                    ')]</value>
      <webElementGuid>45ce046d-2136-44d3-a15e-da339c6477f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
