<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>e4df1a16-fa8d-4858-8b5f-c27b7a1c36b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_side_bar']/aside/ul/li[5]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>509b7121-b56a-4506-ada4-f27f90ca5219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>e5eac8ec-e8f4-4212-9f53-a8b9ac44994e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://badrforsales-test.souqalbadr.top/category</value>
      <webElementGuid>d85969fd-dd7a-47dc-8516-64e2af502ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> التصنيفات</value>
      <webElementGuid>ca285f19-357c-4e41-bec3-0c32c2bcd048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_side_bar&quot;)/aside[@class=&quot;global-aside&quot;]/ul[@class=&quot;sidebar list-group list-unstyled&quot;]/li[@class=&quot;list-group-item dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-side show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>58b5b88c-136b-46d7-a2c1-f9011318cf5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_side_bar']/aside/ul/li[5]/div/a[2]</value>
      <webElementGuid>b7297283-906d-430a-82b2-95b127937422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'التصنيفات')]</value>
      <webElementGuid>23347001-77f6-48f3-ae50-da3614612d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاصناف'])[1]/following::a[1]</value>
      <webElementGuid>e59add3f-b350-4334-97d7-6cdda18c7b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عرض مرتجع مشتريات'])[1]/following::a[3]</value>
      <webElementGuid>703f9f60-ffd5-4811-abe5-4858f14a16db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوحدات'])[1]/preceding::a[1]</value>
      <webElementGuid>8d24a2da-03bc-48c6-91f9-650e934ab03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طباعة التكت'])[1]/preceding::a[2]</value>
      <webElementGuid>1a8887da-5562-4d56-be56-f1f0f67d5f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='التصنيفات']/parent::*</value>
      <webElementGuid>dbbf52e4-df70-43f2-b657-11fe8f3db4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://badrforsales-test.souqalbadr.top/category')]</value>
      <webElementGuid>90d9c229-25af-4ef7-b79a-223a301d37a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a[2]</value>
      <webElementGuid>f589b2db-f2a0-49ef-8638-7287857def24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://badrforsales-test.souqalbadr.top/category' and (text() = ' التصنيفات' or . = ' التصنيفات')]</value>
      <webElementGuid>93cff258-cc19-4627-9b01-e0c3047e8af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
