<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3</name>
   <tag></tag>
   <elementGuidId>60421bd6-1d2b-4f75-a90e-0c520ac37362</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[43]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#printBarcodeForm > div.modal-footer.d-flex.justify-content-end > button.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>010358be-6405-411e-a93d-5c7873f85318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c425f321-d6f3-4f1d-a03d-66b68c9ec78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>803c9d3a-b203-4119-a8a3-7cfc25a97018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>4252f1b0-5e63-4b1e-b516-7ea852911892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إلغاء</value>
      <webElementGuid>844f8935-6686-453b-98d8-22dce8c3a974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;printBarcodeForm&quot;)/div[@class=&quot;modal-footer d-flex justify-content-end&quot;]/button[@class=&quot;btn btn-secondary&quot;]</value>
      <webElementGuid>623a6cce-3980-43b0-b0cf-8aab9e1894d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[43]</value>
      <webElementGuid>a00cd9c1-03aa-41f6-84a5-cbbf10ac1a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='printBarcodeForm']/div[2]/button[2]</value>
      <webElementGuid>892f1363-0a59-42ae-80d4-a1fa339cdac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طباعة'])[1]/following::button[1]</value>
      <webElementGuid>27bc9f5a-a06b-4485-b0a4-f5ce7221b8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الكمية :'])[2]/following::button[2]</value>
      <webElementGuid>df4a9163-43fd-491a-b1d0-0072247250c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/form/div[2]/button[2]</value>
      <webElementGuid>bb221ad1-d59a-486f-b5bb-8cca4b80678f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'إلغاء' or . = 'إلغاء')]</value>
      <webElementGuid>d24d313e-adc1-4d3b-b2e8-5e2623245fc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
