<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1</name>
   <tag></tag>
   <elementGuidId>2c02e0bb-9e78-4779-a782-9f6b53f8aad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='item_form']/div[10]/div/div/button/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8a3aca3-a353-4ca4-a6be-ae04c4a3b2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-option-inner-inner</value>
      <webElementGuid>1e53d3a0-7fbf-4717-9d5d-436f5d895c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>وحدة افتراضي</value>
      <webElementGuid>c71c65c3-cca1-4c8d-bcf3-fd4b2d959f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_form&quot;)/div[@class=&quot;form-row row&quot;]/div[@class=&quot;form-group col-md-6&quot;]/div[@class=&quot;dropdown bootstrap-select form-control col-md-12&quot;]/button[@class=&quot;btn dropdown-toggle btn-light&quot;]/div[@class=&quot;filter-option&quot;]/div[@class=&quot;filter-option-inner&quot;]/div[@class=&quot;filter-option-inner-inner&quot;]</value>
      <webElementGuid>0e711681-2378-4e6f-91e4-b005d5d30b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='item_form']/div[10]/div/div/button/div/div/div</value>
      <webElementGuid>5625dc07-fe3c-40ab-b004-b316762df449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوحدة الاساسية :'])[1]/following::div[4]</value>
      <webElementGuid>1b52b403-9362-4fc3-a212-e77235f2823a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تاريخ إنتهاء الصلاحية :'])[1]/following::div[6]</value>
      <webElementGuid>f65fcfd3-d96e-4bc1-8f3a-6c6ff9321c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصنيف :'])[1]/preceding::div[4]</value>
      <webElementGuid>8c0e5f1d-f4ce-4400-ba0e-3060983855ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تصنيف افتراضي'])[2]/preceding::div[4]</value>
      <webElementGuid>35093450-2c05-4d5b-ab12-b08441d6b2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/button/div/div/div</value>
      <webElementGuid>5a13c53d-5d1f-479e-b402-fdbb2a4b879c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'وحدة افتراضي' or . = 'وحدة افتراضي')]</value>
      <webElementGuid>fc66b9e9-ba58-467a-8399-b777255c74c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
