<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1_2</name>
   <tag></tag>
   <elementGuidId>a913be76-22f5-445f-9373-fb775bbbb491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='purchase_vat_select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#purchase_vat_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>10de37a9-50be-4262-a8ff-3f3fe3c2d736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-12 form-control selectpicker</value>
      <webElementGuid>43c3cf0a-ece7-4ed8-a3cf-98cce4d411ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purchase_vat_state</value>
      <webElementGuid>ada47b3d-85f3-48d4-b6d6-ddfd49960af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchase_vat_select</value>
      <webElementGuid>973966a3-8d70-49f7-a34f-2b4c23034e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>2f36e19a-a6eb-46e9-94c5-b4b02aa8a48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                معفى
                                غير شامل
                                شامل
                            </value>
      <webElementGuid>2b960147-55ef-4c26-bcd7-4766d175a818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchase_vat_select&quot;)</value>
      <webElementGuid>e680b37e-d7ec-4f5b-8db4-180ba4f17d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='purchase_vat_select']</value>
      <webElementGuid>24de6921-c48b-47a0-a901-bdc4b16f8429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='item_form']/div[13]/div/div/select</value>
      <webElementGuid>ccf0291e-0792-467d-9636-5ae8dad25ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing selected'])[1]/following::select[1]</value>
      <webElementGuid>46d36e25-3da5-4b6e-be05-894e6607b830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='معفى'])[4]/preceding::select[1]</value>
      <webElementGuid>e7bb15fc-c1b1-4d9a-91cd-e445f43cf42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='معفى'])[5]/preceding::select[1]</value>
      <webElementGuid>87143a50-33a1-4a2b-acb0-7629758ac596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/select</value>
      <webElementGuid>25982382-c504-4c7e-bde0-2d796595ae4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'purchase_vat_state' and @id = 'purchase_vat_select' and (text() = '
                                معفى
                                غير شامل
                                شامل
                            ' or . = '
                                معفى
                                غير شامل
                                شامل
                            ')]</value>
      <webElementGuid>c5a21888-4c78-4e6c-99c0-d4ecbda571da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
