<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>a6e3de96-c34f-4504-add6-40cdd9052924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-5-1']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-5-1 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3e20e9c-d74f-40f2-9669-826757d2b4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b70a14d-d50e-4de6-af1d-5983634464e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    فلوس
                                </value>
      <webElementGuid>3fe8561d-d6a4-4e5c-95d5-7fe4c47fa5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-5-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>9da7f80a-473d-41ad-acb9-4da90e86fac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-5-1']/span[2]</value>
      <webElementGuid>ae954431-cbb7-4316-b15c-5a0f005c1600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عميل و مورد افتراضي'])[3]/following::span[2]</value>
      <webElementGuid>7d689d69-0151-472d-b8d9-d8a9b42b2e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عميل و مورد افتراضي'])[2]/following::span[4]</value>
      <webElementGuid>12bc4c3c-1882-4498-9b6a-5eb287137ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='فلوسكو'])[2]/preceding::span[2]</value>
      <webElementGuid>94755b77-e87e-486c-b3d5-1dcbdad3a317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span[2]</value>
      <webElementGuid>76941b35-b6ac-4565-b73d-a7ecc17917d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                    فلوس
                                ' or . = '
                                    فلوس
                                ')]</value>
      <webElementGuid>e0a4421d-248b-45d3-a6c4-40face6d52bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
