<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>eee57fc6-4a1d-4ff9-8ca1-cf53f8967e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-6-1']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-6-1 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e90bd5e-c53d-415a-97f4-cbe2893f7c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>752087e9-ccc8-40ec-b26b-6cf9b98ad807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>غير شامل</value>
      <webElementGuid>c6e854fe-51d5-4249-979a-d523753b0b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-6-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>acbb96ba-63e0-48f3-b16d-d7502a081a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-6-1']/span[2]</value>
      <webElementGuid>662a2da5-2c3b-450b-af69-d30c853c3922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='معفى'])[3]/following::span[2]</value>
      <webElementGuid>3f68a9f7-95b6-4d6b-ab07-cf93bafd7396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='معفى'])[2]/following::span[4]</value>
      <webElementGuid>3210155e-5ac1-4838-815b-1cc341313ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='شامل'])[2]/preceding::span[2]</value>
      <webElementGuid>00c1a366-ed50-4764-bc78-cfaa0f5d7f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/ul/li[2]/a/span[2]</value>
      <webElementGuid>163d376f-b045-4ca1-b609-cd2e228b710b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'غير شامل' or . = 'غير شامل')]</value>
      <webElementGuid>185ca31d-a073-47ff-b7b3-a7702618f39e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
