<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__buildingNumber</name>
   <tag></tag>
   <elementGuidId>8900a9ec-dc64-4c84-af5f-74873c5aff08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildingNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buildingNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bf10605-10a4-48fa-903c-775e5de03abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>991b6a43-f37b-4652-9a3a-4be0416ae95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-9</value>
      <webElementGuid>0d0cdcaf-65ed-4a8e-a53a-4b1fc6c3dc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingNumber</value>
      <webElementGuid>91c4695e-504f-4c27-b9f9-d4d5f4f90b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildingNumber</value>
      <webElementGuid>b326b643-3b52-4392-98af-ca4ec7e8e7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingNumber&quot;)</value>
      <webElementGuid>ae541970-78fd-462a-939d-4c0f3a090591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildingNumber']</value>
      <webElementGuid>99049b1b-7436-4fcb-b3a5-5baf91ea326d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>53458e5a-cbc7-4ec2-b3f3-8a4fb57efec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'buildingNumber' and @name = 'buildingNumber']</value>
      <webElementGuid>fb5c75d2-6d35-4dce-bcfc-62f886902df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
