<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>628aaee9-5df6-4ca6-90d4-1d28df517fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='client_role']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client_role</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d739a25d-96c0-41a5-9cf7-e89f503c46db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client_role</value>
      <webElementGuid>c726ccb2-8aa7-4a97-8a22-7ccbc4f89e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client_role</value>
      <webElementGuid>05247785-ef09-4ef4-906f-de4dc6f78312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selectpicker col-md-9</value>
      <webElementGuid>40291c3c-0f1f-436c-a5eb-e920f70dfa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>إختر دور العميل</value>
      <webElementGuid>6a41b045-fcd2-46a2-b04a-11fbef250a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>387ed0d3-04bd-4eba-bbda-5eb35734ebc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            عميل
                                مورد
                                كلاهما
                                                    </value>
      <webElementGuid>bf8412e8-60c8-410b-8a5f-775769210a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client_role&quot;)</value>
      <webElementGuid>5479a14a-8b33-40ee-9d80-75d7b10fec69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client_role']</value>
      <webElementGuid>27b30484-5d0f-49f0-8149-5c9d77bcadb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='دور العميل :'])[1]/following::select[1]</value>
      <webElementGuid>89c74fdf-fbb4-4348-b7d6-ca3ae0b17622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عميل جديد'])[1]/following::select[1]</value>
      <webElementGuid>204b03ce-1647-4ab4-a9e1-a3511c638883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إختر دور العميل'])[1]/preceding::select[1]</value>
      <webElementGuid>02d30e6f-83f1-464b-81a3-a1faac286eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عميل'])[2]/preceding::select[1]</value>
      <webElementGuid>1b2d8a7f-2cc4-4547-afe9-41cdbe13e3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>cd21e24f-0c44-4c32-b3c8-fc99dd762370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'client_role' and @id = 'client_role' and @title = 'إختر دور العميل' and (text() = '
                                                            عميل
                                مورد
                                كلاهما
                                                    ' or . = '
                                                            عميل
                                مورد
                                كلاهما
                                                    ')]</value>
      <webElementGuid>7069357d-dec3-4337-911b-5b787aa52748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
