<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>6ddd98a5-d123-41b1-a99d-3e4ba1cea1eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_side_bar']/aside/ul/li[5]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5c503a0-558d-4f8c-9a56-438cbb9bc7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>15f0f224-09e8-4e4c-aa7f-5c259ccb8a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://badrforsales-test.souqalbadr.top/category</value>
      <webElementGuid>9eaf3358-7510-4769-9ea8-14d1e1c0478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> التصنيفات</value>
      <webElementGuid>b8d4c492-e75f-40aa-bb76-fb4f4c8fee73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_side_bar&quot;)/aside[@class=&quot;global-aside&quot;]/ul[@class=&quot;sidebar list-group list-unstyled&quot;]/li[@class=&quot;list-group-item dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-side show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>8a304517-4c59-4883-8bc7-72fdae7c0913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_side_bar']/aside/ul/li[5]/div/a[2]</value>
      <webElementGuid>8759aeb4-24bb-4b2c-989d-8e6031a207be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'التصنيفات')]</value>
      <webElementGuid>94288767-7231-42e9-b74a-376f4f695688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاصناف'])[1]/following::a[1]</value>
      <webElementGuid>786d4311-6e53-464c-beb4-8fc02bc69c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عرض مرتجع مشتريات'])[1]/following::a[3]</value>
      <webElementGuid>8aed8a06-f291-4cb2-9e4c-51879496b42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوحدات'])[1]/preceding::a[1]</value>
      <webElementGuid>68351903-9c40-4e9c-b37d-f4e52ecd5380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طباعة التكت'])[1]/preceding::a[2]</value>
      <webElementGuid>87ef64ae-92c0-4e42-bd65-40332ed320ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='التصنيفات']/parent::*</value>
      <webElementGuid>08921052-df80-4110-befb-37275fc1aa94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://badrforsales-test.souqalbadr.top/category')]</value>
      <webElementGuid>4dfecbde-56a0-4874-b749-76dc4a13dcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a[2]</value>
      <webElementGuid>adbab4e2-d024-470f-8a13-e39fa2c2f44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://badrforsales-test.souqalbadr.top/category' and (text() = ' التصنيفات' or . = ' التصنيفات')]</value>
      <webElementGuid>789aec97-8456-42c6-b45b-b58ad80b800a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
