<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__image</name>
   <tag></tag>
   <elementGuidId>8e0e76da-a762-4a8a-ad4d-bc2381374238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd8a5dbc-2bd0-47c7-9b4a-8b55bb12a2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>5f6a0ce5-4db8-4490-9040-257caed27e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>29eb40f2-6825-4e23-9115-95494e4c8b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>987f06b1-2062-477f-87c5-8f14f368a4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>8353078d-df40-47b7-be04-207a6a9a9109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image&quot;)</value>
      <webElementGuid>b0a15c9a-3949-4cdc-812b-5570eaaac650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='image']</value>
      <webElementGuid>6ab7f917-9f87-4a23-a6e4-4a43c88097e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-loader-u']/div/div/div/div[2]/input</value>
      <webElementGuid>bbba15fc-6287-456d-afdb-19f2595176fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>27939cda-95c7-454a-b2a1-80deb85c2e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'image' and @id = 'image']</value>
      <webElementGuid>68752bb1-dd74-4d0f-a70d-6551a96ac8bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
