<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>56de16af-b6e1-4664-8dcc-ac21491c3c15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_side_bar']/aside/ul/li[5]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43d431f1-2364-4678-ab98-618733f0796e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>4d6d6471-86a7-4682-bef7-eaec8aa461ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://badrforsales-test.souqalbadr.top/category</value>
      <webElementGuid>1e85cf0d-2961-49e7-8954-02792df13355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> التصنيفات</value>
      <webElementGuid>566193a6-838a-4a4c-ba64-0536d4fe9b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_side_bar&quot;)/aside[@class=&quot;global-aside&quot;]/ul[@class=&quot;sidebar list-group list-unstyled&quot;]/li[@class=&quot;list-group-item dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-side show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>27e80b40-6fde-49f2-b440-be5aa35acf3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_side_bar']/aside/ul/li[5]/div/a[2]</value>
      <webElementGuid>b73afe48-e935-489a-9184-90201ef3de6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'التصنيفات')]</value>
      <webElementGuid>89a019f3-84fc-4267-8d41-bd5bee159215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاصناف'])[1]/following::a[1]</value>
      <webElementGuid>2d1ca542-16c8-47d5-8518-584d434b29f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عرض مرتجع مشتريات'])[1]/following::a[3]</value>
      <webElementGuid>5b4c4121-b1d4-4149-a5f5-847ea6f2adb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوحدات'])[1]/preceding::a[1]</value>
      <webElementGuid>25f25c8c-02bf-456f-a54a-332270f4ee85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طباعة التكت'])[1]/preceding::a[2]</value>
      <webElementGuid>d43965f1-61c4-4990-93b5-9d725d72d1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='التصنيفات']/parent::*</value>
      <webElementGuid>c2e2ddf7-6f4a-4240-8cff-8c3ef9b53a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://badrforsales-test.souqalbadr.top/category')]</value>
      <webElementGuid>1395d577-b20b-4dd4-968a-cbbb1d8532e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a[2]</value>
      <webElementGuid>a8347ad0-fc1a-43ff-8219-3c85979af5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://badrforsales-test.souqalbadr.top/category' and (text() = ' التصنيفات' or . = ' التصنيفات')]</value>
      <webElementGuid>09b78cb3-eac2-4e8c-a58f-a20bc1e1c64a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
